### ISSUE TITLE
Create a Page which can take video from local system and play

### ISSUE THREAD

**Issue by Partha-2000-Snp** [Partha-2000-Snp/TestRepo1TireApp#1]
Create a Page which can take video from local system and play, no login required.
![image](https://github.com/Partha-2000-Snp/TestRepo1TireApp/assets/147611678/7131e548-4098-4877-8b29-8ac57b138092)

**Comment by ParthasarathiPanda** [comment]
Working on it.

**Comment by ParthasarathiPanda** [comment]
done with first task.
